[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

[context.production.environment]
  NETLIFY_SITE_ID = "0cd2575d-eca5-4b91-99fa-9ff78e1400a7"